export interface FCMNotificationItem {
  send: (...data: unknown[]) => void
}

export enum NotificationTypes {
  NEW_MESSAGE = 'NEW_MESSAGE',
  SYSTEM = 'SYSTEM',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NEW_POST_FROM_FOLLOWING = 'NEW_POST_FROM_FOLLOWING',
  POST_ADDED_TO_FAVOURITES = 'POST_ADDED_TO_FAVOURITES',
  FAVOURITE_POST_PRICE_CHANGE = 'FAVOURITE_POST_PRICE_CHANGE',
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  NEW_COMMENT_ON_POST = 'NEW_COMMENT_ON_POST',
  COMMENT_ON_SAME_POST = 'COMMENT_ON_SAME_POST',
  REPLY_ON_POST_COMMENT = 'REPLY_ON_POST_COMMENT',
}
